languageCode = "en-us"
title = "Dopetrope"
baseURL = "http://localhost:1313/"
theme = "../.."

[params]
    subtitle = "Howdy. This is Dopetrope."
    subtitleline2 = "A responsive template by HTML5 UP"

[params.portfolio]
    title = "My Portfolio"
    foldername = "portfolio"
    findoutmoretext = "Find out more"

[params.blog]
    title = "The Blog"
    viewalltext = "View All"
    postsperpage = "6"
    foldername = "blog"

[params.settings]
    googleanalytics = "UA-113904582-1"
    disqus = "hugo-dopetrope"